# Air configuration for github.com/dev-sandip/go-auth

# Root of the project
root = "."
tmp_dir = "bin"

[build]
# Generate Templ templates, then build from ./cmd/app
cmd = "templ generate && go build -o ./bin/app ./cmd/app"

# Binary output
bin = "bin/app"
full_bin = "./bin/app"

# File extensions to watch
include_ext = ["go", "templ", "html", "css", "js"]

# Directories to ignore during file watching
exclude_dir = ["bin", "vendor"]

# Optional: include/exclude fine-grained files
include_dir = []
exclude_file = []
exclude_regex = ["_test\\.go"]
exclude_unchanged = true

# Build delay and error handling
delay = 1000                # milliseconds
stop_on_error = true
send_interrupt = true
kill_delay = 500            # milliseconds

[log]
time = true

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true
